[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar"
healthcheckPath = "/eazystore/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
